### ISSUE TITLE
播放模式：顺序播放/随机播放/单曲循环

### ISSUE THREAD

**Issue by lonelykid** [nondanee/vsc-netease-music#1]
播放列表：删除
播放模式：顺序播放/随机播放/单曲循环

**Comment by lonelykid** [comment]
谢谢，摸鱼利器😁

**Comment by nondanee** [comment]
列表删除有什么好的交互意见吗，还是只是清空？quickPick 只能处理单击选择
播放模式会做的

**Comment by lonelykid** [comment]
意见谈不上，只是觉得现在列表无法控制感觉不大好😂，基本的添加和删除的功能如果实现起来方便的话还是值得的

**Comment by mzlogin** [comment]
需要个删除功能。可以加一个“从播放列表删除”，然后展示播放列表，单击删除。
