### ISSUE TITLE
Code-Server中，应该如何替换ffmpeg（找不到Electron我也不知道应该怎么办，那个库已经发issue了）

### ISSUE THREAD

**Issue by ForeverOpp** [nondanee/vsc-netease-music#100]
有一个浏览器跑VS Code的项目[code-server](https://github.com/cdr/code-server)，大部分VS插件都支持，您的插件也可以正常安装、登陆，但是无法播放音乐，这个vs（1.45.x）找不到electron相关目录。
如果觉得我的问题没有价值，请直接关闭，谢谢。

**Comment by nondanee** [comment]
code-server 是 B-S 的应用，没有 electron 的，也不用换 ffmpeg，你的浏览器默认肯定支持音视频播放

这个我之前也试过
是因为目前播放的音频地址在本地做了一次"代理"，不是真实地址
给webview 的播放地址是这样的 http://localhost:16363/song/<id>

而 code-server 不支持 webview 的 portMapping https://code.visualstudio.com/api/advanced-topics/remote-extensions#option-2-use-a-port-mapping

在浏览器里直接访问 http://localhost:16363 肯定是不通的，所以播不了

做 "代理" 是因为真实地址有 15 分钟时限，如果歌曲/电台节目本身超过 15 分钟，中途会断 (原生没缓存)

要改这个的话还是有点麻烦
方法1. 传真实地址 (15 分钟内)
方法2. 单独开一个公网能访问的"代理"

如果有思路你自己改造下
之后会考虑加个配置

**Comment by ForeverOpp** [comment]
好的，明白了，谢谢。

**Comment by nondanee** [comment]
调研了下发现 code-server 是支持 web 端口映射的
https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#how-do-i-securely-access-web-services
形式是 `/proxy/<port>/` 这样的，插件版本 0.0.42 我适配了，你试试看

**Comment by ForeverOpp** [comment]
太感谢了，这就去看一下！
