### ISSUE TITLE
只有NeteaseMusic: Start指令

### ISSUE THREAD

**Issue by xiaxingtao** [nondanee/vsc-netease-music#102]
刚装完插件可以用的，关闭了vscode之后再次启动就只有NeteaseMusic: Start。

**Comment by xiaxingtao** [comment]
应该是公司网络的问题，用自己的热点就可以登录，有指令，但是用公司的网就没有。但是公司的网用网易云客户端没有问题。

**Comment by nondanee** [comment]
应该是公司 DLP 证书的问题，设置里可以不使用 https 接口，或者关闭证书校验
