### ISSUE TITLE
自动化脚本建议

### ISSUE THREAD

**Issue by sky5454** [nondanee/vsc-netease-music#103]
关于安装路径，VSCode 安装时写入环境变量 Path
**所以可以这样获得其安装路径**
- Windows
```cmd
where code
```

 - Linux
```bash
whereis code
```

**版本信息**
可以从  `.\Microsoft VS Code\resources\app\package.json` 文件里获得
![image](https://user-images.githubusercontent.com/12370628/91380813-753e3a80-e858-11ea-838a-db56a3337c35.png)
![image](https://user-images.githubusercontent.com/12370628/91380802-72434a00-e858-11ea-8f26-ddeb9cb41ebc.png)

**ffmpeg 可以从这里下载单独文件，不用解压完整包**
https://github.com/electron/electron/releases/tag/v7.3.2
如
![image](https://user-images.githubusercontent.com/12370628/91382523-82f5bf00-e85c-11ea-92c9-51579a9795f5.png)
> 另外，我觉得应该保留原版的 ffmpeg，例如改名为 ffmpeg.dll.bak

**Comment by nondanee** [comment]
1. 安装路径一直都有用这个途径取
2. 版本号确实可以取到，但是 arch 取不到，win/linux 上还是有 32 位的，64 位系统也可以装 32 位的程序
3. ffmpeg 替换下载整个包有历史原因 https://github.com/nondanee/vsc-netease-music/issues/66#issuecomment-532124604

保留源文件是怕换了启动不了吗？换了应该不会影响功能啊
脚本执行多次的话命名还要额外处理

**Comment by nondanee** [comment]
关于取 electron 版本的问题
找旧版看了下大概从 1.42.x 开始在 package.json 里才有 electron 版本号，而且是放在 devDependencies 里的
写脚本的时候应该还拿不到
已改成优先从本地拿
