### ISSUE TITLE
Linux Automatic Replacement Error

### ISSUE THREAD

**Issue by shawndebuggggg** [nondanee/vsc-netease-music#105]
Replaced in "sudo su" in Linux, run into this error
vsc 1.48.2
electron 7.3.2

```
root@hz-VirtualBox:/home/hz# curl https://gist.githubusercontent.com/nondanee/f157bbbccecfe29e48d87273cd02e213/raw | python3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3304  100  3304    0     0  23600      0 --:--:-- --:--:-- --:--:-- 23600
Traceback (most recent call last):
  File "<stdin>", line 55, in <module>
AssertionError
```

**Comment by nondanee** [comment]
The script runs `which code` but not find your VS Code installation path
https://gist.github.com/nondanee/f157bbbccecfe29e48d87273cd02e213#file-helper-py-L20
Please download the script, fill the installation path in line 20 `installation = '/some/path'` and rerun it
