### ISSUE TITLE
更新VScode 1.49.0版本后无法使用该插件

### ISSUE THREAD

**Issue by SernRounder** [nondanee/vsc-netease-music#106]
使用上个版本可以正常使用插件, 更新到最新版本后出现了控制台中只有网易云音乐:启动选项的情况, 选择后会弹出窗口, 但是控制台里还是只有启动选项. 确认不是host或者其他配置的原因. 在我的另一台还未更新到最新版本vscode的电脑上能够正常使用, 更新后立刻出现了上述问题
也许是vscode的更新导致了不兼容?

**Comment by Althrone** [comment]
同样情况，昨晚（9月12日）发现了，以为是自己的网络或者设置问题，今早装回1.48.2版本，然后替换对应dll就没事了
环境：windows10
官方的1.48.2版本下载连接：https://code.visualstudio.com/updates/v1_48

**Comment by nondanee** [comment]
看了下是 webview 的 api 变了
```diff
- panel.postMessage()
+ panel.webview.postMessage()
```

**Comment by uniquezl** [comment]
版本: 1.58.2 (user setup)
提交: c3f126316369cd610563c75b1b1725e0679adfb3
日期: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 6.1.7601

同样遇到这个问题。
