### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by qcq** [nondanee/vsc-netease-music#107]
try to use this feature, found below:

NotSupportedError: Failed to load because no supported source was found.

**Comment by liyishuai** [comment]
RTFM: https://github.com/nondanee/vsc-netease-music#requirement

**Comment by willin** [comment]
no use,  vsc crashed

**Comment by nondanee** [comment]
solution for crashing https://github.com/nondanee/vsc-netease-music/issues/86#issuecomment-786546931
