### ISSUE TITLE
调出命令面板后，CTRL+v无法使用

### ISSUE THREAD

**Issue by rfhits** [nondanee/vsc-netease-music#109]
# 无法复制粘贴

1. Ctrl+Shift+V打开命令面板

2. 选择“网易云音乐：登陆”

3. 按下Ctrl+V，没有反应

按下Windows+V调出粘贴记录，选择也没有用。

**Comment by rfhits** [comment]
我不想把cookie一个个敲进去，呜呜呜。。

**Comment by nondanee** [comment]
在播放器的 webview 里不让粘贴，随便切换个 tab 就能粘贴了

好像是这个问题 https://github.com/microsoft/vscode/issues/65452

我看看

**Comment by nondanee** [comment]
还有这些

https://github.com/microsoft/vscode/issues/101599  
https://github.com/microsoft/vscode/issues/101201

应该是 vscode 自身的问题
