### ISSUE TITLE
下一首/上一首/暂停 热键支持

### ISSUE THREAD

**Issue by Illyrix** [nondanee/vsc-netease-music#11]

**Comment by nondanee** [comment]
这个一直在 todo 里面，觉得设置成什么好？顺手的快捷键一般都被其它功能占用了...
shortcuts 得预设，固定在 package.json 里，不支持用户自定义。

**Comment by Illyrix** [comment]
> 这个一直在 todo 里面，觉得设置成什么好？顺手的快捷键一般都被其它功能占用了...
> shortcuts 得预设，固定在 package.json 里，不支持用户自定义。
@nondanee 
直接用网易云默认全局的吧(Ctrl+Alt+←, Ctrl+Alt+→, Ctrl+Alt+P

**Comment by wi24rd** [comment]
默认不要设置吧，留一个配置给用户自己设置自己喜欢的。

**Comment by nondanee** [comment]
@Illyrix 这个已经被用了
Ctrl+Alt+Right | Move Editor into Next Group | workbench.action.moveEditorToNextGroup
Ctrl+Alt+Left | Move Editor into Previous Group | workbench.action.moveEditorToPreviousGroup
参见 https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by nondanee** [comment]
@wi24rd 自定义实现不了==，必须 hard coding，除非自己打包 vsix
参见 https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings

**Comment by wi24rd** [comment]
除此之外还要考虑各平台 DE 快捷键，比如 Ctrl+Alt+Right/Left 有些 DE （比如 xfce，没记错的话，GNOME 就是 Ctrl+Alt+Up/Down）是切 workspace。
需要考虑的因素可能还有其他的，所以我觉得这个功能可以先放下，个人感觉 Ctrl-Shift-P 然后模糊搜索已经够方便了，到时候造成冲突反而不好。

**Comment by zaylezou** [comment]
提供一个建议 alt+， alt+. alt+/

**Comment by Chuck-Ray** [comment]
![image](https://user-images.githubusercontent.com/63182083/85089675-d5d84800-b215-11ea-990c-64d34b53e314.png)
