### ISSUE TITLE
播放没有声音

### ISSUE THREAD

**Issue by NuoLoci** [nondanee/vsc-netease-music#110]
作者你好，自从升级为electron 9.3.5版本之后，像往常一样下载了相应版本的ffmpeg.dll放入VScode安装文件夹中，打开插件时有显示播放，也能执行搜索歌单等功能，但播放时却没有任何的声音
![image](https://user-images.githubusercontent.com/41853910/102079122-102e4500-3e47-11eb-9185-08b308b023c4.png)
![image](https://user-images.githubusercontent.com/41853910/102079197-2fc56d80-3e47-11eb-96b6-df497b8863fd.png)
![image](https://user-images.githubusercontent.com/41853910/102079217-39e76c00-3e47-11eb-93f9-cf536d133c20.png)

**Comment by Smoovsky** [comment]
+1， 升级1.52.0后没有声音

**Comment by Rona-dt** [comment]
+1 相同情况
![image](https://user-images.githubusercontent.com/57215192/102169126-77daa380-3ecc-11eb-95b4-d85f09a3a865.png)

**Comment by EdisonJwa** [comment]
在1.15.2 的版本中遇到了相同的问题，刚刚测试了insider版本 (1.53.0-insider) 版本是能正常播放的
> 1.53.0-insider 版本所用 Electron 版本为 11.0.3

**Comment by ZhuLinsen** [comment]
> 作者你好，自从升级为electron 9.3.5版本之后，像往常一样下载了相应版本的ffmpeg.dll放入VScode安装文件夹中，打开插件时有显示播放，也能执行搜索歌单等功能，但播放时却没有任何的声音
> ![image](https://user-images.githubusercontent.com/41853910/102079122-102e4500-3e47-11eb-9185-08b308b023c4.png)
> ![image](https://user-images.githubusercontent.com/41853910/102079197-2fc56d80-3e47-11eb-96b6-df497b8863fd.png)
> ![image](https://user-images.githubusercontent.com/41853910/102079217-39e76c00-3e47-11eb-93f9-cf536d133c20.png)

me too

**Comment by nondanee** [comment]
发现了，暂时解决不了 😭

你们用这个吧 https://marketplace.visualstudio.com/items?itemName=yxl.cloudmusic&ssr=false#overview

**Comment by nondanee** [comment]
😥 检查了下发现是歌曲资源重定向导致的，那可能可以修好，周末试试

**Comment by Smoovsky** [comment]
> 😥 检查了下发现是歌曲资源重定向导致的，那可能可以修好，周末试试

GJ

**Comment by PengDingkang** [comment]
当在 WSL2 中使用扩展时，依然没有声音
本地使用没有问题

**Comment by nondanee** [comment]
@PengDingkang
看了下是内部重定向导致的
试了下只打开一个 remote 是有声音的

先在本地打开了插件，再到 remote 里也打开了插件就没声音 (反过来操作好像不会)
因为 remote 的 server 需要在本地做端口映射，默认是原端口号映射，不用重定向
本地插件开着会占用端口，需要重定向，一重定向就没声音

**Comment by nondanee** [comment]
@PengDingkang 试一下 0.0.44

**Comment by PengDingkang** [comment]
> @PengDingkang 试一下 0.0.44

解决了，谢谢！
