### ISSUE TITLE
macOS沒辦法用

### ISSUE THREAD

**Issue by ab15963qw** [nondanee/vsc-netease-music#111]
我把路徑下的vscode的libffmpeg.dylib 替摸成 11.2.1的版本；可是沒想到vscode 就不能開？

**Comment by allinu** [comment]
OS: Big sur
最新版的vscode
使用Automatic方式安装完毕后

打开直接崩溃（打不开）

**Comment by nondanee** [comment]
参考这个 https://github.com/nondanee/vsc-netease-music/issues/86#issuecomment-786546931
