### ISSUE TITLE
无法安装，与Code "1.25.1"不兼容

### ISSUE THREAD

**Issue by UniqueAlex** [nondanee/vsc-netease-music#12]
自动安装不了，手动下载安装会报这个错，所以1.25.1版本是不能用吗？

**Comment by UniqueAlex** [comment]
忘记说了，是macOS

**Comment by nondanee** [comment]
没试过，可能可以，理论上有 webview 的版本 (1.23 以上) 就行了。
最低 engine 是 [generator-code](https://github.com/Microsoft/vscode-generator-code) 生成的， 应该是我建项目时用的 VS Code 版本，就没去改。

可是为什么不升级呢，不是会自动升级的吗==

**Comment by nondanee** [comment]
试过了
1.27 以上才行
1.26 Webview 不正常
1.25 及以下 command not found，应该是注册机制不一样
