### ISSUE TITLE
3.19出现的新问题 - NeteaseMusic My: Mix 创建/收藏歌单不显示

### ISSUE THREAD

**Issue by suniyao** [nondanee/vsc-netease-music#129]
今天使用插件的时候发现NeteaseMusic My: Mix里面只有自己红心的歌单，创建和收藏的歌单都不见了，重新启动插件好像也没有用，想知道是只有我有这个问题还是大家都有？
![image](https://github.com/nondanee/vsc-netease-music/assets/121154397/1262a3af-1ed5-48c6-9efd-959aefcaa3ec)

**Comment by suniyao** [comment]
问题已解决，这个算是网易云的bug，好像过一段时间就会登出，桌面版的网易云也一样，现象都是只能看到喜欢的歌曲，其他的歌单看不到。解决方式只要log out再log in就可以了

**Comment by PLASTA0728** [comment]
问题已解决，这个算是网易云的bug，好像过一段时间就会登出，桌面版的网易云也一样，现象都是只能看到喜欢的歌曲，其他的歌单看不到。解决方式只要log out再log in就可以了
