### ISSUE TITLE
好像没有个人FM?

### ISSUE THREAD

**Issue by wi24rd** [nondanee/vsc-netease-music#13]
可以加到todo里吗？

**Comment by nondanee** [comment]
可以，不过因为 FM 没有播放列表，和现在的模式是异构的，要动的地方比较多

**Comment by wi24rd** [comment]
播放列表是什么意思？个人使用过[musicbox](https://github.com/darknessomi/musicbox/)可以显示最近的播放列表（只是偶尔需要播放完列表最后的歌曲已有列表才能继续更新列表，没记错的话播放到提前几首的时候也会更新）。不过可能是因为调用API所以网易不能跟踪用户的播放动作（这点是我发现听歌排名那里没有记下历史）所以有的时候会重复之前的（这种情况下手动红星几首歌曲就会有新的曲目）。

**Comment by wi24rd** [comment]
不过我用[这个](https://github.com/nicehiro/netease-music)的时候，他的电台也会有问题，不知道跟这个问题差不多还是因为我姿势不对（题外话

**Comment by nondanee** [comment]
FM 是一首一首请求的，没有播放列表，所以播放下一首的逻辑和现在不一样，在 FM 下部分按钮和命令要屏蔽。听歌记录可以实现。
