### ISSUE TITLE
NeteaseMusic 命令无效

### ISSUE THREAD

**Issue by EdisonJwa** [nondanee/vsc-netease-music#17]
无法使用 `NeteaseMusic` 命令，但是 `网易云音乐` 可用

![网易云音乐](https://i.yecdn.com/images/2019/03/14/226990be4ae459bc30767d95e451cb7f.png)
![NeteaseMusic](https://i.yecdn.com/images/2019/03/14/588233415f9a74693fe4390e23bff7dc.png)

**Comment by nondanee** [comment]
在扩展商店安装中文语言包

**Comment by EdisonJwa** [comment]
还有这种操作  谢谢大佬
