### ISSUE TITLE
好奇一下

### ISSUE THREAD

**Issue by agate** [nondanee/vsc-netease-music#19]
请问你是如何发现 `X-Real-IP` 这个 header 可以让海外用户使用的呀

**Comment by nondanee** [comment]
不是我发现的，不过这个应该已经流传很广了吧==
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/29#issuecomment-298357483 (Node.js API)
[acgotaku/NetEaseMusicWorld](https://github.com/acgotaku/NetEaseMusicWorld) (Chrome 扩展)
[ITJesse/UnblockNeteaseMusic](https://github.com/ITJesse/UnblockNeteaseMusic) / https://www.jianshu.com/p/27bdf38df190 (Koa)
https://jixun.moe/post/ymusic-hosts-fix/ (NGINX 反代)
https://github.com/fengjueming/unblock-NetEaseMusic/issues/17 (NGINX 反代)
[mengskysama/163-Cloud-Music-Unlock](https://github.com/mengskysama/163-Cloud-Music-Unlock) (NGINX 反代)
[azureplus/163-music-unlock](https://github.com/azureplus/163-music-unlock) (NGINX 反代)
