### ISSUE TITLE
Document or hint status bar buttons

### ISSUE THREAD

**Issue by liyishuai** [nondanee/vsc-netease-music#22]
I was trying to play my list randomly instead of looping as preset, but the icons are not informative (I understand it's partly a VS Code issue). I ended up reading the controller's source code to figure it out:
https://github.com/nondanee/vsc-netease-music/blob/e955783f8571bcc87ed5054601de6e7c9610d54e/controller.js#L48
It'll be helpful for us users to show hints upon hovering over the buttons, or have their functionalities documented somewhere.

**Comment by nondanee** [comment]
Ok, I will add tooltips for buttons
