### ISSUE TITLE
对部分命令的建议

### ISSUE THREAD

**Issue by zaylezou** [nondanee/vsc-netease-music#23]
在播放状态下，该指令相当于暂停；在暂停状态时，该指令相当于播放。这样就可以用一个热键去控制播放暂停了，比较方便。另外，静音/取消静音我觉得也可以使用这样的交互逻辑。最后，能否添加音量增加/减小？

**Comment by nondanee** [comment]
emmm 个人感觉命令名字叫做"播放/暂停(自动)"就特别将就，因为命令名字是不能动态改，所以做了两个分开的命令，并且做了状态同步实现互斥，不会同时显示(这比合并成单个命令麻烦的多)。
加快捷键可能会遇到冲突问题，之后我试试会不会有优雅实现，现阶段在命令面板中使用应该只会显示当前有效操作的啊？！
最后，音量调节不是有吗？

**Comment by zaylezou** [comment]
现有的音量调节是五档轮换…希望有更方便的调节方式。不过谢谢！这个插件已经基本满足我的需求了。

**Comment by nondanee** [comment]
是感觉不能向前调节还是觉得档数(5)太少？向前调节我觉得不是问题吧，连续盲按几下就好了。之后会做 exit point 保留上一次退出时的配置

**Comment by nondanee** [comment]
btw 之前音量调节是想分开写 5 个命令的，要在命令面板里显示当前音量大小也只能这么做，后来放弃了😂

**Comment by nondanee** [comment]
我发现 keybindings 和 commandPalette 可以同时使用！
现在设置了 auto.play.pause 和 auto.mute.unmute 指令来响应热键事件自动判断执行正向或是逆向操作，并在命令面板中始终隐藏这两个命令，算是比较优雅的实践了。

**Comment by cserbo** [comment]
这要怎么开始用啊？？ 摸索半天不知道咋弄的

**Comment by nondanee** [comment]
@cserbo 看 README ，有演示啊！

**Comment by nondanee** [comment]
@cserbo 我没懂？不用打开，这是个独立的“客户端”。查看歌单用不了？建议新建一个 issue

**Comment by nondanee** [comment]
现在支持恢复上次退出时的状态了，我想音量大小也不需要经常调吧
音量减小我就不单独做了，这个 issue 我关了哈
