### ISSUE TITLE
侧边栏支持

### ISSUE THREAD

**Issue by Gaojianli** [nondanee/vsc-netease-music#24]
现阶段的歌单选择还是非常不方便，能否考虑增加左侧侧边栏支持来进行歌曲的选择。

**Comment by nondanee** [comment]
是想纯鼠标操作吗？键盘的话应该是从面板最快捷
真实情况是，当时研究过 treeview，但是给的实例代码没看懂怎么用😅

**Comment by nondanee** [comment]
没觉得歌单选择不方便啊
就两步吧，Ctrl + Shift + P > "我的歌单"（最近使用的命令会在最顶上）
"非常"何以见得？

看了下文档，要写 TreeDataProvider 的话改动非常大，不像 quickPick 那么简单灵活
交互部分几乎是要重写了，如果有 PR 再说吧
