### ISSUE TITLE
搜索无反应，发现功能报错

### ISSUE THREAD

**Issue by Kaifu96** [nondanee/vsc-netease-music#33]
使用Search没有反应
使用Discover: High Quality Mix时提示: Unexpected token < in JSON at position 0
已替换ffmpeg

**Comment by nondanee** [comment]
抱歉，这个问题我无法复现

如果你有 node 环境，可以自行单独测试 API 可用性
把 request.js 最后一行注释掉
https://github.com/nondanee/vsc-netease-music/blob/8668047f0aee4ef37cc14dfa3794577c158b0ec6/request.js#L132

然后
```javascript
const api = require('./request.js')
api.playlist.highquality().then(data => console.log(data))
```
