### ISSUE TITLE
"unable to verify the first certificate"

### ISSUE THREAD

**Issue by MorsLin** [nondanee/vsc-netease-music#36]
开启后选择功能时会出现"unable to verify the first certificate"而无法使用

win7 ×64，替换ffmpeg没有作用

**Comment by nondanee** [comment]
或许是这个问题 https://github.com/alibaba/anyproxy/issues/318

**Comment by nondanee** [comment]
因为根证书不被 nodejs 信任，可以 skip，之后加个设置选项
