### ISSUE TITLE
评论过长无法查看

### ISSUE THREAD

**Issue by xiligey** [nondanee/vsc-netease-music#38]
只能显示固定长度的评论，太长的评论后面都是...了

**Comment by nondanee** [comment]
已知问题，quickpick 限制了 label，detail，description 都只能显示一行

现在设为 detail ，鼠标放上去是可以显示全部(hover 的效果)

**Comment by xiligey** [comment]
> 已知问题，quickpick 限制了 label，detail，description 都只能显示一行
> 
> 现在设为 detail ，鼠标放上去是可以显示全部(hover 的效果)

3Q
