### ISSUE TITLE
503

### ISSUE THREAD

**Issue by ShiweiCao** [nondanee/vsc-netease-music#39]
Mac版，人在海外，文件也替换了，但是播放不了，webview developer tools 显示status code 503，在浏览器中打开可以播放

![Screen Shot 2019-04-12 at 11 14 40 AM](https://user-images.githubusercontent.com/17609594/56057954-07ea4200-5d15-11e9-867d-08d306210d45.png)

**Comment by nondanee** [comment]
这个链接复制到浏览器不会 503 ？那在浏览器打开的 headers 也贴一下
5xx 是服务器的问题，我比较难办啊==

**Comment by ShiweiCao** [comment]
忘了当时试的哪首歌，重新截了两张，是不是解析的歌曲地址哪里出了点错误

VSC里的
![Screen Shot 2019-04-12 at 9 13 28 PM](https://user-images.githubusercontent.com/17609594/56074458-05fd9e80-5d68-11e9-8c67-db18da44efe0.png)

浏览器里的
<img width="973" alt="Screen Shot 2019-04-12 at 9 14 11 PM" src="https://user-images.githubusercontent.com/17609594/56074463-0f870680-5d68-11e9-8682-e6ce9d931fb4.png">

看了下直接网页播放的
<img width="972" alt="Screen Shot 2019-04-12 at 9 18 08 PM" src="https://user-images.githubusercontent.com/17609594/56074501-9b009780-5d68-11e9-83dc-a8050582ff33.png">

**Comment by nondanee** [comment]
把 m8c 改成 m8 试试
可能是 CDN 的问题

**Comment by ShiweiCao** [comment]
试了下，m8仍然是503

**Comment by ShiweiCao** [comment]
我在同一个网络下的windows版可以正常工作，这是同一首歌的response
![image](https://user-images.githubusercontent.com/17609594/56075318-4fa0b600-5d75-11e9-886d-b8c2c7d8b847.png)

**Comment by nondanee** [comment]
这就没办法了
查查看有没有改过 hosts，自定义过 CDN 吧

**Comment by ShiweiCao** [comment]
host除了上班用到的把 localhost.*.com 映射到 127.0.0.1，其他都没动过

**Comment by nondanee** [comment]
老哥后来有解决吗？

**Comment by ShiweiCao** [comment]
不好意思一直没注意回复，我最近试的还是不行，似乎解析的地址还是不对，看起来是只有我才有的问题？没看到其他人提起这个issue
