### ISSUE TITLE
F1 命令行过滤需要精确到字符串， 不匹配的话命令就消失了， 其他程序的命令不需要这么精确

### ISSUE THREAD

**Issue by shynome** [nondanee/vsc-netease-music#43]
复现步骤：
- 按 `F1` 调出命令框
- 输入 `music next`
- 可选命令只剩 0 个， 预期的是 `下一首` 命令会留下

预期效果：
像 `settings sync` 那样输入 `sync upload` 会留下 `上传设置` 命令

**Comment by nondanee** [comment]
next 命令是有快捷键的

匹配是 vscode 提供的，我感觉好像是个 bug
`netease next` 就可以匹配到，`music next` 就不行
可能是 Music 有个大写的原因==

**Comment by shynome** [comment]
vscode 好像是开头第一个字母来匹配的，像 `ne next` 就可以匹配到

下意识用 `music` 搜索命令搜不到还以为是 bug 。。。

**Comment by nondanee** [comment]
确实，不是大小写的问题，要从第一个字母开始匹配 category 才支持多关键字匹配
用 `yth` 可以匹配到 python 前缀的命令，但是 `yth run` 就没有结果了，而 `pyt run` 就可以
应该是 vscode 自己的策略
