### ISSUE TITLE
播放没有声音

### ISSUE THREAD

**Issue by aaronxdd** [nondanee/vsc-netease-music#46]
下载了插件但是播放的时候没有声音

**Comment by nondanee** [comment]
你 New issue 的时候没有显示 related 的吗？
![image](https://user-images.githubusercontent.com/26399680/58364035-52e4a100-7ee0-11e9-8fa4-5d7eee2d0b4b.png)

麻烦把 README 好好看一遍谢谢
Duplicate #2 #4 #9 #35 #37 #45
