### ISSUE TITLE
如何更加灵活的调节音量?

### ISSUE THREAD

**Issue by zhen8838** [nondanee/vsc-netease-music#47]
我在Ubuntu下,系统的音量无法调节vscode的播放音量,vscode中的20%就是最大音量的20%,感觉还是太响...

请问如何更灵活地调节音量?

**Comment by zhen8838** [comment]
修复了系统音量调节错误

**Comment by nondanee** [comment]
这个 "修复了系统音量调节错误" 没看懂😂 
所以是你自己的问题？

**Comment by zhen8838** [comment]
恩.排查了一下是pulseaudio的问题.现在可以通过系统音量控制vscode音量了....

**Comment by nondanee** [comment]
好的👌
