### ISSUE TITLE
請問如何查看收藏了的歌單或者歌曲？

### ISSUE THREAD

**Issue by winsonet** [nondanee/vsc-netease-music#49]
首先非常喜歡這個插件，先謝啦！！！

我點了收藏后，但不知如何找出來，是不是在我的音樂里？但當點了后就會出現以下錯誤：
```Cannot read property 'creator' of undefined```

其實每當我登錄時都會出現錯誤說登錄失敗，錯誤如下：
```登录失败: 未知错误(undefined)```

但好像又已登錄進去了~~，因為可以讓我收藏和登出了

其實好像所有關於```我的```功能都用不了，我的專輯或者歌曲都會出現以下錯誤：
```Cannot read property 'map' of undefined```

我是在windows 10下使用的

**Comment by nondanee** [comment]
应该是登录的问题
你试一下在插件上收藏/喜欢歌曲会不会在客户端同步

**Comment by winsonet** [comment]
哦，終於發現原因了，其實我是第一次使用網易音樂，所以還沒登錄過網頁端去設置過暱稱，所以登錄時總是出錯，導致其實根本沒連接上我的帳號 .......

Thanks!

**Comment by nondanee** [comment]
好的
