### ISSUE TITLE
vscode June 2019 (version 1.36)插件失效

### ISSUE THREAD

**Issue by Xianbei233** [nondanee/vsc-netease-music#52]
正常操作逻辑，显示正常播放，无声音传出

**Comment by BIN9o** [comment]
同样

**Comment by moonxy** [comment]
> 同样

我一开始也是这样 ,但当我登陆以后突然就有了声音,或许你们可以试试

**Comment by moonxy** [comment]
同样 vscode更新到1.36后 播放无声音   浏览器打开也跳转不到相关歌曲页面  链接为 https://music.163.com/#%2Fsong%3Fid%3D1369601580

**Comment by nondanee** [comment]
替换一下 ffmpeg.dll 试试？#50

**Comment by Xianbei233** [comment]
emmmm,替换哪的？vscode内也只有vscodeLive带这个dll，还是说去electron里翻？ @nondanee

**Comment by Xianbei233** [comment]
还有替换成哪家哪个版本的ffmpeg.dll ？

**Comment by nondanee** [comment]
@Xianbei233 
vscode 根目录应该有 ffmpeg.dll 吧？
README 里有说明

**Comment by Xianbei233** [comment]
Ok，fixed, electron version:[4.1.0](https://github.com/electron/electron/releases/tag/v4.1.0) 替换dll后work

**Comment by nondanee** [comment]
@moonxy 
等 vscode 那边修复 https://github.com/microsoft/vscode/issues/76606
