### ISSUE TITLE
[Feature Request] 有没有可能增加对vscode remote的支持

### ISSUE THREAD

**Issue by TTTPOB** [nondanee/vsc-netease-music#54]
我现在日常的工作环境是连接到服务器上进行编辑，但此时似乎没有办法用这个插件。
（本地的时候真的很好用）

**Comment by nondanee** [comment]
看了下应该做个 port mapping 就行了
https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api

**Comment by nondanee** [comment]
翻了下文档好像对 websocket 端口有点问题，不过说是 another port，不知道 same port 可不可以
https://code.visualstudio.com/api/references/vscode-api#WebviewOptions

**Comment by nondanee** [comment]
试过了 websocket 端口确实没法转发

改成长轮询已经可以用了，可以用 vsix 先试试
https://send.firefox.com/download/4d4022d957e3e6de/#0v2WbrEik-xgtoucS1Prgg

我再试试看用 SSE

**Comment by TTTPOB** [comment]
确实可以用了万分感谢！
