### ISSUE TITLE
在打开的网页上加一些内容

### ISSUE THREAD

**Issue by Nekomio** [nondanee/vsc-netease-music#56]
感觉开一个空的界面不是很美观，希望能加入一些内容。
比如正在播放的歌曲，歌词，或者，控制面板之类的东西。

**Comment by nondanee** [comment]
啊因为那个空页不是必需的，因为没法隐藏只好留着
正在播放歌曲在 more 中显示，也会有 message 提示
歌词和控制都在 statusbar 中，控制也可以通过快捷键和 command palette

**Comment by Nekomio** [comment]
既然不能隐藏，为什么不美化一下呢?

**Comment by nondanee** [comment]
因为没有必要啊 =.=
而且感觉那样跟直接用网页版没区别了

**Comment by Nekomio** [comment]
关键是好丑啊， 加一个logo什么的都可以啊

**Comment by nondanee** [comment]
(啊可是一般不会点到那个 tab 吧)

**Comment by Nekomio** [comment]
emmm, 那好吧

**Comment by nondanee** [comment]
(考虑加一个 app 的开屏页)
但是要抠图 =.= 缓缓

**Comment by moonxy** [comment]
领导在的时候不小心切换到     还在么愉快的摸鱼~   我觉得现在的就不错

**Comment by alex2wong** [comment]
@Nekomio 如果要加点啥进度条，可视化效果，你可以自己加。。然后vsce package 自己再安装下。。比如这样的 #63 
我把我本地做的 VSIX release 在forked 的项目里了，喜欢可以下载玩玩：
https://github.com/alex2wong/vsc-netease-music/releases/tag/0.0.24

不过原来的听歌体验挺好的，比较纯粹，眼睛累了就听听歌，不用看屏幕哈哈：）
