### ISSUE TITLE
支持AirPods控制

### ISSUE THREAD

**Issue by wandergis** [nondanee/vsc-netease-music#59]

**Comment by nondanee** [comment]
大概查了下

不知道用 electron 的 globalShortcut 注册过
MediaNextTrack、MediaPreviousTrack、MediaStop 和 MediaPlayPause 可不可以实现
有两个相关的 issue 
https://github.com/trazyn/ieaseMusic/issues/351
https://github.com/ilime/Petal/issues/37

如果可以的话就尝试用 [iohook](https://github.com/wilix-team/iohook) 注册快捷键（因为 vscode 不提供 globalShortcut API）

但是我现在既没有 macOS 设备也没有 Airpods......

**Comment by nondanee** [comment]
麻烦测试一下 vscode 1.40 上 AirPods 控制是否可用？
理论上接了 Media Session API 应该就可以了
谢谢

**Comment by wandergis** [comment]
666 已测试是ok的

**Comment by nondanee** [comment]
好滴👌
