### ISSUE TITLE
issue: please interact with the document first otherwise play( ) will failed

### ISSUE THREAD

**Issue by buerlee** [nondanee/vsc-netease-music#6]
when input netease start

it shows "please interact with the document first otherwise play( ) will failed"

My OS is Win 10

Thank you.

**Comment by nondanee** [comment]
Just follow the instruction, 'click' anywhere in that webview page
This step is required due to Chrome Autoplay Policy.

**Comment by buerlee** [comment]
Got it. thanks a lot for your so fast response.

**Comment by mxmingya** [comment]
I got the same error and clicking on the webview didnt resolve it. 

got following details from pop out tabs. 

"Please interact with the document first otherwise play() will failed"

**Comment by nondanee** [comment]
@mxmingya 

Is there any error raising (like "NotSupportedError") ? #73 #75 #78 
Do you replace the ffmpeg dynamic lib before ? 
(refer to https://github.com/nondanee/vsc-netease-music#requirement)

Or maybe something work wrong in the webview
Press `F1` and choose the `Open Webview Developer Tools`, You can see the console log of the Webview

**Comment by GangLongYu** [comment]
> @mxmingya
> 
> Is there any error raising (like "NotSupportedError") ? #73 #75 #78
> Do you replace the ffmpeg dynamic lib before ?
> (refer to https://github.com/nondanee/vsc-netease-music#requirement)
> 
> Or maybe something work wrong in the webview
> Press `F1` and choose the `Open Webview Developer Tools`, You can see the console log of the Webview

我的webview报错是`Uncaught TypeError: Cannot read property 'setActionHandler' of undefined
    at <anonymous>:77:27`，neteaseMusic界面只有`Please interact with the document first otherwise play() will failed`，vscode版本是1.39.2，electron是4.2.10，请问有什么解决方法吗，非常感谢

**Comment by GangLongYu** [comment]
> > @mxmingya
> > Is there any error raising (like "NotSupportedError") ? #73 #75 #78
> > Do you replace the ffmpeg dynamic lib before ?
> > (refer to https://github.com/nondanee/vsc-netease-music#requirement)
> > Or maybe something work wrong in the webview
> > Press `F1` and choose the `Open Webview Developer Tools`, You can see the console log of the Webview
> 
> 我的webview报错是`Uncaught TypeError: Cannot read property 'setActionHandler' of undefined at <anonymous>:77:27`，neteaseMusic界面只有`Please interact with the document first otherwise play() will failed`，vscode版本是1.39.2，electron是4.2.10，请问有什么解决方法吗，非常感谢

更新版本之后就可以了，感谢您的插件
