### ISSUE TITLE
每次放到最后就卡住

### ISSUE THREAD

**Issue by Ibuki-Suika** [nondanee/vsc-netease-music#61]
每次快放到结尾的时候就会突然卡住（没有声音，像是被暂停了一样），然后大概过十几秒又会自动继续播放（期间没有人为操作）
然后控制台就会提示
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
截图：
https://ae01.alicdn.com/kf/H02454be5aadb414e929e527efc9eeccfd.png

emmmmmm但是又不是每首歌都这样，感觉看脸，一会好一会坏（坏的概率>=50%）。。。

其他功能都正常

坐标国内
普通用户

vscode版本：
```
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```

**Comment by nondanee** [comment]
是哪首歌能不能提供一下，我去查一下

国内的话去设置里把 `NeteaseMusic.CDN.redirect` 这个选项关掉试试看

**Comment by Ibuki-Suika** [comment]
测试歌曲：https://music.163.com/#/song?id=411500648
试了一下，在redirect关掉的情况下倒是没有卡住的现象，但是报错还是一样的：
https://ae01.alicdn.com/kf/Hcfd04a4a396f41dbb3534c71cb8c8af3l.png
然后又把redirect开启，还是一样的报错，同时到结尾卡住了：
https://ae01.alicdn.com/kf/H7efc3dae6acc4002bd00ce822c1d2b13t.png

好奇怪。。。

**Comment by nondanee** [comment]
我试了下我这里不会报 `ERR_CONTENT_LENGTH_MISMATCH`
可能各地的 CDN 配置不一样吧=.= 不太清楚

你 ping 一下 `m8c.music.126.net`，IP 告诉我

**Comment by Ibuki-Suika** [comment]
```
Pinging m8c.music.126.net.wsdvs.com [111.202.43.101] with 32 bytes of data:
Reply from 111.202.43.101: bytes=32 time=5ms TTL=54
Reply from 111.202.43.101: bytes=32 time=7ms TTL=54
Reply from 111.202.43.101: bytes=32 time=5ms TTL=54
Reply from 111.202.43.101: bytes=32 time=5ms TTL=54

Ping statistics for 111.202.43.101:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 5ms, Maximum = 7ms, Average = 5ms
```

**Comment by nondanee** [comment]
我改了 hosts 也没法复现 =.=
而且我这边报错是 `net::ERR_CONNECTION_RESET 206 (Partial Content)` 这个
不知道为什么

**Comment by Ibuki-Suika** [comment]
_(:з)∠)_
