### ISSUE TITLE
PR: Do you like music visualization?

### ISSUE THREAD

**Issue by alex2wong** [nondanee/vsc-netease-music#63]
Thank you for providing such good extension~~ I suppose we can add some more feature like **music visualization**. I've made one yesterday, tested locally. If you think it is OK, I'd like to send a PR.

snapshot as follows:
![vscode_vudio](https://user-images.githubusercontent.com/10528482/64496866-f1eca780-d2db-11e9-92e5-cc179758d035.gif)

Technically, [vudio.js](https://github.com/alex2wong/vudio.js) was imported for audio visualization. Current issue is that I can **NOT** get song cover from existing request API, could you guys just add a cover img url attr for song API ?  then I can rotate it in the circular : )

**Comment by nondanee** [comment]
Related issue #56 
Honestly, I have no plan to add UI elements to webview page
Thanks, anyway
You can package your customized version to .vsix and install for personal use

Cover img url will be added to song object very soon : )

**Comment by alex2wong** [comment]
Sure, thanks a lot : )
Actually this kind of feature can be optional, user can enable/disable it by controllers or keyboard shortcut. It cost some GPU/memory resource indeed  and can attract unnecessary  attention. 

Looking forward the cover img url, thanks again.
