### ISSUE TITLE
Issue with installation on Linux

### ISSUE THREAD

**Issue by hyt589** [nondanee/vsc-netease-music#65]
Hi, I tried to install the extension on VS code version 1.38.0, Linux, which required the `libffmpeg.so` to be replaced. I tried your script, and it contained an error at line 55, which was actually caused by an invalid shell command invoked at line 54. Then I modified the script by changing `'./'` to `''`, and it ran successfully. However, the plugin still does not work for me, i.e. there's no sound. Any ideas why?

Here is the output of `code --version`:
```
1.38.0
3db7e09f3b61f915d03bbfa58e258d6eee843f35
x64
```
Btw, VS Code was actually installed via snap on my system.

And my system info `cat /etc/os-release`:
```
NAME="Zorin OS"
VERSION="15"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 15"
VERSION_ID="15"
HOME_URL="https://www.zorinos.com"
SUPPORT_URL="https://www.zorinos.com/help"
BUG_REPORT_URL="https://bugs.launchpad.net/zorin-os"
PRIVACY_POLICY_URL="https://www.zorinos.com/legal/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Comment by hyt589** [comment]
Turns out it was the issue with the snap installation path. I deleted my original installation and downloaded directly from VS Code and this time it worked.

**Comment by nondanee** [comment]
👌
