### ISSUE TITLE
可以不可以直接放ffmpeg的下载地址啊

### ISSUE THREAD

**Issue by LinearPi** [nondanee/vsc-netease-music#66]
可以不可以直接放 需要替换的ffmpeg的下载地址啊？

**Comment by LinearPi** [comment]
https://github.com/electron/electron/releases

**Comment by LinearPi** [comment]
![image](https://user-images.githubusercontent.com/29011350/65009722-4deca700-d940-11e9-8a89-e69d48622908.png)

**Comment by nondanee** [comment]
你试过了可以用吗？

在刚开始写插件的时候我试过，能播放 ogg 格式但是 mp3 没法播放

所以 README 里明确写了
> 下载对应的 **Electron 完整版本**进行替换

我去试试看现在行不行

**Comment by LinearPi** [comment]
> 你试过了可以用吗？
> 
> 在刚开始写插件的时候我试过，能播放ogg格式但是mp3没法播放
> 
> 所以README里明确写了
> 
> > 下载对应的**电子完整版本**进行替换
> 
> 我去试试看现在行不行

我可以使用了，你可以下载上面的 electron对应的版本，解压后用里面的ffmpeg.dll 替换vscode里面就可以使用了

**Comment by nondanee** [comment]
我试了 4.2.10 的能播放

不过那个独立的 ffmpeg 包，和 electron 里那个 dll 确实不太一样
![image](https://user-images.githubusercontent.com/26399680/65014836-5e0d8200-d952-11e9-845f-ed16bff7d4aa.png)

我去试试之前的版本

**Comment by LinearPi** [comment]
![image](https://user-images.githubusercontent.com/29011350/65015542-7088bb00-d954-11e9-84d6-ba90d9c3798a.png)
我试了两个都是可以的。

**Comment by nondanee** [comment]
嗯？electron 6.0.9 可以用？vscode 现在最新版才用 4.2.10 啊

**Comment by LinearPi** [comment]
> 嗯？electron 6.0.9 可以用？vscode 现在最新版才用 4.2.10 啊

vscode 和 electron 有对应的版本嘛？

**Comment by nondanee** [comment]
当然有啊

![image](https://user-images.githubusercontent.com/26399680/65016498-00c7ff80-d957-11e9-905f-b5e1efb7abc0.png)

README 里写了
> 通过 VS Code 版本在 https://raw.githubusercontent.com/Microsoft/vscode/%version%/.yarnrc 查看其使用的 Electron 版本

**Comment by LinearPi** [comment]
嗯嗯

**Comment by nondanee** [comment]
我测过了

## vscode 1.30.2 (最后一个用 electron 2.x 的版本)
- 换任何 electron 2.x 的 ffmpeg.dll 都可以启动
- 但必须用 electron 里的 ffmpeg.dll 替换，用单独提供 ffmpeg 替换还是会报 NotSupportedError，无法播放

## vscode 1.35.1 (最后一个用 electron 3.x 的版本)
- 换任何 electron 3.x 的 ffmpeg.dll 都可以启动
- 用单独提供 ffmpeg 替换即可以播放

## vscode 1.36.0 (第一个用 electron 4.x 的版本)
- 换任何 electron 4.x/5.x/6.x 的 ffmpeg.dll 都可以启动
- 用单独提供 ffmpeg 替换即可以播放


**稳妥起见还是用对用的 electron 完整版替换，大部分人用脚本，也不会在意这个问题**

**Comment by LinearPi** [comment]
> 我测过了
> 
> ## vscode 1.30.2 (最后一个用 electron 2.x 的版本)
> * 换任何 electron 2.x 的 ffmpeg.dll 都可以启动
> * 但必须用 electron 里的 ffmpeg.dll 替换，用单独提供 ffmpeg 替换还是会报 NotSupportedError，无法播放
> 
> ## vscode 1.35.1 (最后一个用 electron 3.x 的版本)
> * 换任何 electron 3.x 的 ffmpeg.dll 都可以启动
> * 用单独提供 ffmpeg 替换即可以播放
> 
> ## vscode 1.36.0 (第一个用 electron 4.x 的版本)
> * 换任何 electron 4.x/5.x/6.x 的 ffmpeg.dll 都可以启动
> * 用单独提供 ffmpeg 替换即可以播放
> 
> **稳妥起见还是用对用的 electron 完整版替换，大部分人用脚本，也不会在意这个问题**
/zan  /zan
