### ISSUE TITLE
no other commands show than the command "netease music: start"

### ISSUE THREAD

**Issue by sunnysunny3145** [nondanee/vsc-netease-music#67]
So appreciate this extension. 

I successful open VS code and run the command "netease music: start". However, no other commands show when I'm trying to search netease related commands after pressing F1. I entered the page "Please preserve this webview tab" already. It is my first time to use it. Any recommands? 

My OS: windows 10
VS code version: 1.38.1
electron version: 4.2.10
already replace the ffmpeg.dll manually.

**Comment by nondanee** [comment]
I test with the same environment as yours but can not reproduce the error.

Be sure that your VS Code can access network. (No offline mode at present #62)

In startup phase, the extension will connect to NeteaseMusic server for checking the account login status and daily sign status, also fetching user's favorite songs (in `component.refresh` method)

https://github.com/nondanee/vsc-netease-music/blob/1c4d969ae449b69716ede4b9652c26ee7dcbdb07/runtime.js#L403-L407

**Comment by sunnysunny3145** [comment]
> I test with the same environment as yours but can not reproduce the error.
> 
> Be sure that your VS Code can access network. (No offline mode at present #62)
> 
> In startup phase, the extension will connect to NeteaseMusic server for checking the account login status and daily sign status, also fetching user's favorite songs (in `component.refresh` method)
> 
> https://github.com/nondanee/vsc-netease-music/blob/1c4d969ae449b69716ede4b9652c26ee7dcbdb07/runtime.js#L403-L407

Thanks a lot for your help. I tried it in another PC which works. I guess it is the proxy configuration problem. The failed one need to go through a http proxy to access the internet. The VS code follow my browser's proxy configuration so that I can download apps without any problem. It looks like the vsc-netease-music didn't go through proxy correct. Is there any way to configure this extension on the proxy with user name and passcode? So appreciates. XD

**Comment by nondanee** [comment]
I checked the issue https://github.com/Microsoft/vscode/issues/12588#issuecomment-530719673

The official says they have already patched on `http` and `https` modules for extension.

> **Just** authentication does not work

I test and the requests from my extension really bypass the `http.proxy` set in setting.json.
So I will not do extra work but wait the official support for proxy authentication.

Thank you for your understanding.

**Comment by sunnysunny3145** [comment]
> I checked the issue [microsoft/vscode#12588 (comment)](https://github.com/microsoft/vscode/issues/12588#issuecomment-530719673)
> 
> The official says they have already patched on `http` and `https` modules for extension.
> 
> > **Just** authentication does not work
> 
> I test and the requests from my extension really bypass the `http.proxy` set in setting.json.
> So I will not do extra work but wait the official support for proxy authentication.
> 
> Thank you for your understanding.

So glad we found the reason. XD Appreciate your help.
