### ISSUE TITLE
启动后没有任何反应

### ISSUE THREAD

**Issue by Althrone** [nondanee/vsc-netease-music#69]
运行后状态栏的播放条没有出现，命令面板输入netease依旧只有启动的命令
电脑出现过dns的问题，导致网页之类的上不了，当时情况类似，但是现在只有这个插件用不了（vsc的插件商城也能正常使用）

**Comment by nondanee** [comment]
浏览器可以打开 [网易云官网](http://music.163.com) 吗? 
证书正确吗 (颁发者是 GeoTrust RSA CA 2018)？

插件设置里 https://github.com/nondanee/vsc-netease-music#extension-setting
`NeteaseMusic.API.SSL` 和 `NeteaseMusic.SSL.strict` 可以分别关掉试试看

**Comment by Althrone** [comment]
上面都尝试过 然后甚至连vscode都重装过了（差点重装电脑）
刚去了同学那里试了下，没敢卸载他的插件，但是logout了 之后login出现未知错误（账号密码都没问题）

**Comment by Althrone** [comment]
然后刚刚他登录他自己的账号正常，我又logout了一次 登陆我的账号，现在弄到他电脑也用不了了（我要被鲨了）

**Comment by Althrone** [comment]
猜测是login logout的bug 但是我看不懂源码

**Comment by nondanee** [comment]
我刚才 logout 登了另一个账号，再登录回来都没问题
可能是你账号的问题，请邮件联系我一下

**Comment by nondanee** [comment]
手动清数据的方式可能比较麻烦，等我写个指南 （你不会 si 的）
