### ISSUE TITLE
lrc 歌词解析不完美

### ISSUE THREAD

**Issue by outloudvi** [nondanee/vsc-netease-music#7]
lrc 文件允许同一行出现多个时间轴。状态栏的歌词显示器对此类格式似乎解析不完美。

例如：[juunana/NGC 3.14 - Remnants](https://music.163.com/#/song?id=423406940) 在播放至约 1:16 秒时显示的歌词：
```
[03:32.02]All I want is for those memories to last 我最后想要的，只是重温过去美好的回忆。
```

**Comment by nondanee** [comment]
感谢反馈
