### ISSUE TITLE
你好，这边有无法播放的问题

### ISSUE THREAD

**Issue by jiandandema** [nondanee/vsc-netease-music#70]
作者你好
先谢谢你开发这个插件。我这边有一个问题想请教你。我已经替换了ffmpeg。在Please interact with the document first otherwise play() will failed界面中，我随便点击鼠标，页面也没有什么变化。而且我在F1里面输入命令，也只有一个neteasemusic。
希望可以得到解答，谢谢！

**Comment by nondanee** [comment]
F1 里面找一下 
```
开发者: 打开 Webview 开发工具
开发者: Open Webview Developer Tools
```

看看 console 报什么错

**Comment by jiandandema** [comment]
貌似是报错：NotSupportedError Failed to load because no supported source was found.
![image](https://user-images.githubusercontent.com/51021076/67789581-29dbc400-faaf-11e9-8baf-f7ae6baa6bd0.png)
不好意思，编程新手很多都还不太懂，麻烦了。。。

**Comment by nondanee** [comment]
报这个错应该是替换的没成功
不过 insider 版我没测试过能不能用，有空我试试

**Comment by jiandandema** [comment]
嗯嗯，好的，谢谢你了！

**Comment by nondanee** [comment]
修复了
是 insider 版才有的问题
更新 electron 后原来的 load local resource 方法有 BUG
not support error 报错信息不太准确

还有现在这个 insider 版本会绑定 Windows 音量条的媒体控制，目前有点丑，下一版更新
