### ISSUE TITLE
之前还能用的，现在不知道怎么回事，重新换了ffmpeg也没用。

### ISSUE THREAD

**Issue by NH333** [nondanee/vsc-netease-music#71]
NotAllowedError play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
data:text/html;char…:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by nondanee** [comment]
我这边没问题啊
是什么版本，insider ？

**Comment by NH333** [comment]
版本: 1.39.2 (user setup)
提交: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
日期: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by NH333** [comment]
非 insider 版本

**Comment by NH333** [comment]
刚看了下，别的功能都正常，就是歌听不了

**Comment by nondanee** [comment]
一般来说报 'Failed to load because no supported source was found.' 这个错就是没替换
你再替换一次吧

**Comment by hantmac** [comment]
> 一般来说报 'Failed to load because no supported source was found.' 这个错就是没替换
> 你再替换一次吧

Mac 版本的vscode怎么替换？

**Comment by nondanee** [comment]
@hantmac 
README 里有写哈 (不区分系统版本的)
