### ISSUE TITLE
安装完之后只有一个neteasemusic.start命令，其他neteasemusic都没有

### ISSUE THREAD

**Issue by wingscrazy** [nondanee/vsc-netease-music#72]
执行start 后可以成功：Please preserve this webview tab

版本: 1.40.0 (user setup)
提交: 86405ea23e3937316009fc27c9361deee66ffbf5
日期: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by nondanee** [comment]
我测了没问题啊，不过我是 system setup
安装完之后确实只有一个命令，等 webview tab 打开后才有其他的命令
你看看是不是使用方法的问题，可以看一下 README 里的操作演示图

**Comment by nondanee** [comment]
对了
启动要保证有网
如果有网络审计的话在设置里关闭 ssl 证书校验或者不使用 https 接口

**Comment by wingscrazy** [comment]
> 对了
> 启动要保证有网
> 如果有网络审计的话在设置里关闭 ssl 证书校验或者不使用 https 接口

可以了，就是这个问题，谢谢
