### ISSUE TITLE
NotSupportedError

### ISSUE THREAD

**Issue by yanshil** [nondanee/vsc-netease-music#73]
![image](https://user-images.githubusercontent.com/8177510/68606239-06842200-047c-11ea-95d5-c2af2271b87b.png)

加载出现Please interact with the document first otherwise play() will failed提示时点击页面会在右下角弹出这个error.

彻底uninstall vs code 进行重装依然无效。

**Comment by nondanee** [comment]
https://github.com/nondanee/vsc-netease-music#requirement 这个看过吗？

**Comment by yanshil** [comment]
嗯，我之前每个版本都会替换一次的。忘记替换的时候和今天这个error表现不一样，是能点击出现下一个play()的提示界面而不是弹出error，所以没联想到这个。该再试一下的。

（但我发现了你另一个替换灰链的proejct所以我直接换用unblockneteasemusic并且卸载了vs code的插件[捂脸]。

我吃完饭回来测试一下= =

**Comment by nondanee** [comment]
之前确实是不提示的
因为 echo payload 写错了……
https://github.com/nondanee/vsc-netease-music/commit/6d0fadf5dd24913af921b6f9aded733a6436a704

这个 not supported error 就是提醒替换的
1.40 应该不需要 interact 

哦那个项目可以和插件一起用的
两个项目用途不一样

settings 里 HTTPS 开关关掉，然后改个 hosts 就行

**Comment by yanshil** [comment]
OK是的，就是忘记替换咯。大概是哪次给我自动更新之后没留意到~
（echo修好大家出现这个error来看issue的时候就知道咋个解决了[捂脸]）

**Comment by nondanee** [comment]
好的👌
