### ISSUE TITLE
自动跑脚本出错

### ISSUE THREAD

**Issue by JH46666** [nondanee/vsc-netease-music#74]
系统环境：
版本: 1.40.2
提交: f359dd69833dd8800b54d458f6d37ab7c78df520
日期: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
执行代码：
 sudo curl https://gist.githubusercontent.com/nondanee/f157bbbccecfe29e48d87273cd02e213/raw | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3260  100  3260    0     0   1434      0  0:00:02  0:00:02 --:--:--  1434
报错信息：
vscode 1.40.2 x64
Traceback (most recent call last):
  File "<stdin>", line 61, in <module>
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nondanee** [comment]
```
curl https://raw.githubusercontent.com/Microsoft/vscode/1.40.2/.yarnrc
```
正常吗？
