### ISSUE TITLE
启动时遇到问题‘no supported source was found’

### ISSUE THREAD

**Issue by Scared-Heart** [nondanee/vsc-netease-music#75]
NotSupportedError: Failed to load because no supported source was found.
![image](https://user-images.githubusercontent.com/26789238/70763674-e05de480-1d8f-11ea-83f6-a38dc5fcfc97.png)

**Comment by nondanee** [comment]
> [VS Code 使用的 Electron 版本不包含 ffmpeg](https://stackoverflow.com/a/51735036)，需替换自带的 ffmpeg 动态链接库才能正常播放 (每次更新 VS Code 都需重新替换)

每次更新 VS Code 都需重新替换!
每次更新 VS Code 都需重新替换!
每次更新 VS Code 都需重新替换!

Duplicate #73
