### ISSUE TITLE
脚本更新出错

### ISSUE THREAD

**Issue by a982027400** [nondanee/vsc-netease-music#76]
执行python脚本时报错，之前都没问题。如图：
![image](https://user-images.githubusercontent.com/25918335/70764790-9aa31b00-1d93-11ea-99cd-d5e8c85793c2.png)

**Comment by a982027400** [comment]
重新执行一次有好了。。。
![image](https://user-images.githubusercontent.com/25918335/70764872-e05fe380-1d93-11ea-9873-60ca3553a62c.png)

**Comment by nondanee** [comment]
网络问题

gist.github.com 和 raw.githubusercontent.com
部分被墙导致的
