### ISSUE TITLE
每次打开都报错请问是为什么？

### ISSUE THREAD

**Issue by shmilybaozi** [nondanee/vsc-netease-music#78]
![image](https://user-images.githubusercontent.com/36563636/71452950-c8408900-27c3-11ea-83f5-c1a933b96d67.png)

**Comment by shmilybaozi** [comment]
1.41版本

**Comment by shmilybaozi** [comment]
没有替换 ffmpeg

**Comment by nondanee** [comment]
https://github.com/nondanee/vsc-netease-music/blob/master/README.md#requirement

Duplicate #73 #75
