### ISSUE TITLE
增加红心/取消红心图标的区分度

### ISSUE THREAD

**Issue by BoruiGu** [nondanee/vsc-netease-music#80]
经常难以区分这两个图标，以至要先鼠标悬停上去确认下文字再点，希望可以更明显的区分开

![image](https://user-images.githubusercontent.com/8686167/73540723-ae1b4b80-43fe-11ea-8358-aae53c82ef36.png)
![image](https://user-images.githubusercontent.com/8686167/73540727-af4c7880-43fe-11ea-81b7-1ce729d0a4c1.png)

**Comment by nondanee** [comment]
这个我看看

现在用的颜色是 50% 透明度的白色
获取主题色是可以的，但是给主题色加透明度比较麻烦 
因为主题色只是个引用，没有具体值 https://github.com/Microsoft/vscode/issues/32813#issuecomment-466791752

之前试过把按钮改成 "默认前景色/红色" 但是效果不太好

**Comment by BoruiGu** [comment]
或者改成使用两个不同的图标？

**Comment by im0qianqian** [comment]
是否可以用两个 emoji 代替呢？比如 🖤 和 💖

**Comment by nondanee** [comment]
改成动态取主题色加透明度了
