### ISSUE TITLE
网络配置怎么改都显示“Please preserve this webview tab”

### ISSUE THREAD

**Issue by squarefw** [nondanee/vsc-netease-music#81]
关闭ssl和禁用https都尝试了，一直显示Please preserve this webview tab。
最新版本的vs code，ffmpeg也用自动脚本更新了。没辙了。

**Comment by squarefw** [comment]
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by nondanee** [comment]
一直都是 Please preserve this webview tab 啊，有什么问题吗？
交互都在 command palette 内，在 webview 里不会有任何显示
使用方法看 README，有动图演示

**Comment by nondanee** [comment]
@squarefw 

不好意思
一直显示 Please preserve this webview tab 是正常的
你想表达的是不是只有 `NeteaseMusic: Start` 这一个命令？
参考 #67，你的网络环境是有带 authorization 的 http 代理吗？这个不支持

**Comment by squarefw** [comment]
发现了，还是ssl认证的问题，一打开这个就不行了。
现在可以用了，tks

**Comment by nondanee** [comment]
@squarefw 好的👌
