### ISSUE TITLE
个人向：怎么disable右下角的popup。如果觉得每次点掉麻烦

### ISSUE THREAD

**Issue by Zzealer** [nondanee/vsc-netease-music#82]
Go to .vscode/extensions/{MusicCloudPackage}/runtime.js
Comment out Line 339
Restart Vscode

**Comment by nondanee** [comment]
会加一个设置项

**Comment by wangyx1107** [comment]
确实有这个需要，今天找了一圈没有找到disable，每次都弹出感觉没有必要 :)

**Comment by nondanee** [comment]
加了 `NeteaseMusic.Popup.appearance` 设置项
