### ISSUE TITLE
找不到自建歌单

### ISSUE THREAD

**Issue by Rando1f** [nondanee/vsc-netease-music#84]
在登陆成功之后，可以搜索并播放，但是似乎不能看到我所收藏的歌单，也不能播放这些歌单。
我也没有在输入>neteasemusic: 这个前缀之后看到任何可能和歌单相关的命令，似乎只有一个把当前音乐加入歌单？
请问该怎么看到自己建的歌单，或者如何播放它们呢？

**Comment by Rando1f** [comment]
找到了是>NeteaseMusic My: Mix

**Comment by nondanee** [comment]
对，命令有分类的
https://github.com/nondanee/vsc-netease-music/blob/c6c6796b06009997c8df75ecba0027597dcc2e3a/package.nls.json#L42-L46

NeteaseMusic: 播放状态歌曲控制
NeteaseMusic My: 我的 (收藏相关)
NeteaseMusic Discover: 发现 (新歌 / 排行榜)
NeteaseMusic Recommend: 推荐 (日推 / fm 等)
