### ISSUE TITLE
只有neteasemusic.start一个命令可以执行，别的命令都找不到无法执行

### ISSUE THREAD

**Issue by 83chameleon** [nondanee/vsc-netease-music#85]
执行neteasemusic.start后弹出NeteaseMusic标签页，上面只显示 Please preserve this webview tab ，点击无反应，输入其他命令会提示没有匹配的命令，请问是什么问题？最新版的vscode版本1.42.1，我看其中自带了ffmpeg.dll，出现上述问题，我去下载了对应版本的ffmpeg.dll进行替换还未解决

**Comment by nondanee** [comment]
vscode 所有版本都自带 ffmpeg.dll 但是是不完整的，需要替换

你的问题不是 ffmpeg 的问题
是没有网络或者请求失败了的问题，参考 #67 #81 

因为启动过程中会请求登录状态、签到状态、红心歌单数据，如果请求失败了就启动不了

目前应该还是不支持带 authentication 的代理
可以关掉插件设置里的证书校验，或者关掉 https 请求试一下

**Comment by 83chameleon** [comment]
明白了，谢谢大大
