### ISSUE TITLE
vscode 1.43.1 macOS not load vsc-netease

### ISSUE THREAD

**Issue by diegofn** [nondanee/vsc-netease-music#87]
Hello,

![Screen Shot 2020-03-22 at 10 08 11 AM](https://user-images.githubusercontent.com/981273/77252917-1d563480-6c25-11ea-9603-208377aab6f1.png)

I have vscode 1.43.1 on Catalina macOS. This version already include the libffmpeg.dylib but I get the following error when I trying the load the netease extension.

I run the script to copy the libffmpeg version from electron and I receive the same error.
I install vscode 1.36.1, install the extension and I get the same error.

Is there any way to get your help.

Thanks for all.

**Comment by nondanee** [comment]
Any version of VS Code include libffmpeg.dylib
You can regard it as a "placeholder"

VS Code 1.43.x will crash at start after lib replacement #86 
The error log shows `EXC_BAD_ACCESS (Code Signature Invalid)`
You can turn off SIP (System Integrity Protection) if you have urgent need with this extension

In short, VS Code Webview can not play audio anymore after 1.43.x
I will change the implement for macOS as soon as possible

The extension should be worked in 1.36.1, but still need replacing ffmpeg lib

**Comment by diegofn** [comment]
Thanks for your help.
I will wait for a new version.

**Comment by masnn** [comment]
The same problem.

**Comment by xiaoweiz** [comment]
Running the script to do the automatic replacement will lead to crash on my machine, exactly as reported. However, I went to the Electron repository to download the proper release version and did a manual replacement of the `libffmpeg.dylib` file. It then worked. 

I'm not sure the reason, but hope this info can be of help.

**Comment by nondanee** [comment]
@xiaoweiz 
So what is "the proper release version" ?
The automatic script use the electron mirror from taobao npm instead of official repository
I will check it soon
THX

**Comment by xiaoweiz** [comment]
The version indicated by the script, e.g. electron 7.1.1 for vscode 1.43.3

**Comment by nondanee** [comment]
@xiaoweiz 
Thank you for your feedback
The automatic script use `shutil.copyfileobj` for file replacement
https://stackoverflow.com/a/30359308
Because `shutil.copyfileobj` can not overwrite metadata, maybe the mismatched metadata cause crash
I update script and add `os.remove` to ensure the whole file can be replaced completely

You can continue using the automatic replacement
It should work now

**Comment by diegofn** [comment]
Hello, Its works for me. Thank you  :-)
