### ISSUE TITLE
【使用求助】运行后没反应

### ISSUE THREAD

**Issue by GareArc** [nondanee/vsc-netease-music#88]
刚刚在VSC中装了插件，也确认过election的版本并且替换了ffmpeg.dll。启动之后页面显示了Please preserve this webview tab.然后我在命令行里还是只找到start命令，啥也没发生...
![Image 1](https://user-images.githubusercontent.com/52963600/78101777-90df0b00-73b6-11ea-8b41-f2d4c9a85c64.png)

**Comment by nondanee** [comment]
应该是初始化失败了
是不是没网？网络有审计吗？安装过根证书吗？
参考 #67 #81 #85

**Comment by GareArc** [comment]
> 应该是初始化失败了
> 是不是没网？网络有审计吗？安装过根证书吗？
> 参考 #67 #81 #85

都看过了，我禁用了http，ssl还是一样，网肯定有的。

**Comment by GareArc** [comment]
是不是需要把host里面加的东西删掉才能用

**Comment by nondanee** [comment]
理论上不需要，你可以试试看

**Comment by GareArc** [comment]
解决了，把host清空然后关ssl就好了。
