### ISSUE TITLE
NotSupportedError: Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by qianyigengwu** [nondanee/vsc-netease-music#89]
NotSupportedError: Failed to load because no supported source was found.

**Comment by 5ME** [comment]
我也是这个问题，启动时报错，是需要什么环境吗

**Comment by ttdyce** [comment]
Same error here, see 
https://github.com/nondanee/vsc-netease-music#requirement
and 
https://github.com/nondanee/vsc-netease-music/issues?q=NotSupportedError

**Comment by ttdyce** [comment]
> Same error here, see
> https://github.com/nondanee/vsc-netease-music#requirement
> and
> https://github.com/nondanee/vsc-netease-music/issues?q=NotSupportedError

而且snap store版本的VSCode 好像改不了 libffmpeg.so :(

**Comment by nondanee** [comment]
Duplicate #73 #75 #78

**Comment by nondanee** [comment]
@ttdyce 知道安装位置就行啊，为啥改不了？

**Comment by nondanee** [comment]
@ttdyce 查了下 snap 是只读的，那没办法了 :(
