### ISSUE TITLE
mac 上使用没有声音！！已跑自动替换脚本！

### ISSUE THREAD

**Issue by xiaochenaier** [nondanee/vsc-netease-music#9]
已经跑了自动替换的命令，终端输出
vscode 1.32.1 x64
electron 3.1.3
download well
replace done
remove temp

mac系统版本 mojava 10.14.3

**Comment by nondanee** [comment]
重启一次 VS Code？我去试试

**Comment by xiaochenaier** [comment]
@nondanee 关了几次再打开了，不管用。。。

**Comment by nondanee** [comment]
emmm 我试了下没问题， 你在大陆还是海外？
如果可以的话可以帮助 debug 吗，clone 跑一下源码看看

**Comment by Combo819** [comment]
海外，Mac , 没有声音。
同一网络下 Windows有声音
以及，希望能支持weibo登录
@nondanee

**Comment by nondanee** [comment]
@Combo819 微博登录无法实现，除非用户愿意手动复制 cookie

**Comment by nondanee** [comment]
@xiaochenaier @Combo819 
试试打开 VS Code 开发者工具，看看会不会提示什么错误
可能因为 CDN 的证书？感觉会是什么安全问题，不过我无法复现，境外，系统是 capitan 10.11。

如果可以的话，clone 一下源码，npm install，f5 调试跑一下，应该就知道了。

**Comment by plrectco** [comment]
Ubuntu 18.04 无法播放，developer tool报的错是
[Embedded Page] Uncaught (in promise) NotSupportedError: Failed to load because no supported source was found.  
单独把歌曲url拿出来到浏览器中是可以播放的。

**Comment by xiaochenaier** [comment]
@nondanee 我是大陆~我看看VS Code的开发者工具有没有报错，最近才转用vs code，不太熟悉。

**Comment by yq314** [comment]
我在海外，一样mac上没有声音

**Comment by nondanee** [comment]
@yq314 @plrectco 
用 webview tools 打开看一下 network，感谢
`F1` 命令面板里面 "开发者：打开 Webview 开发工具" / "Developer: Open Webview Developer Tools"

**Comment by xiaochenaier** [comment]
卧槽，什么都没动竟然有声音了。。。神奇！（昨天跟现在不一样的地方是公司网络直接能上谷歌，家里不行，挂了个vpn)。。。

**Comment by yq314** [comment]
Network看起来正常
![Screenshot 2019-03-13 at 14 29 56](https://user-images.githubusercontent.com/2336852/54258111-9182e480-459c-11e9-9369-3e09e3f72a17.png)

**Comment by nondanee** [comment]
@yq314 那应该是替换的问题了，手动替换试一下吧

**Comment by nondanee** [comment]
@xiaochenaier 回家看一下 webview tools 的 network

**Comment by hellomrbigshot** [comment]
遇到同样的问题，坐标杭州=。=

**Comment by nondanee** [comment]
@hellomrbigshot 截图 webview tools 的 network

**Comment by yq314** [comment]
跑了好几遍自动替换脚本，每次跑完都会自动更新一个版本，终于在1.32.1版本可以了 👍

**Comment by nondanee** [comment]
@yq314 那是因为你太久不更新吧😂

**Comment by nondanee** [comment]
@hellomrbigshot 那，检查更新吧，等更新到 1.32.1 再替换

**Comment by hellomrbigshot** [comment]
> @hellomrbigshot 那，检查更新吧，等更新到 1.32.1 再替换

好奇怪，我默认位置安装 vs code 但是跑替换失败了
提示
```

```

> @hellomrbigshot 那，检查更新吧，等更新到 1.32.1 再替换

替换了三次终于成功了😂

**Comment by nondanee** [comment]
@hellomrbigshot 👌

**Comment by nondanee** [comment]
@Combo819 @plrectco 解决了吗？

**Comment by liyishuai** [comment]
更新两次后成功
> vscode 1.32.3 x64
electron 3.1.6

**Comment by nondanee** [comment]
总结一下
**README 中已强调每次 VS Code 更新会覆盖旧文件，需重新替换**
若因为这个插件打开了很久没打开过的 VS Code，为了提高效率，请先点击侧边栏齿轮，选择 "检查更新"
确定已升至最新版本，或者设置 `"update.channel": "none"` 关闭自动更新后
再用脚本或者手动替换 ffmpeg 动态链接库

若怀疑是网络问题请打开 Webview 调试工具检查，并贴上错误信息反馈给我

因为这个 issue 暂时没有回应我就先关闭了，还有问题的话各位可以 Reopen，抱歉啦

**Comment by bestRenekton** [comment]
大佬 mac 没有声音 ，跑替换脚本报错了
vscode 1.32.3 x64
Traceback (most recent call last):
  File "<stdin>", line 58, in <module>
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nondanee** [comment]
@bestRenekton 多试试，或者用一下代理，还不行就手动替换吧

**Comment by zlq4863947** [comment]
赞 我也是这个问题，没声音。 
更新到vscode最新版就可以了

**Comment by ofcZsgj** [comment]
Win10，VS CODE版本为1.33.1，打开插件播放没有声音
执行自动脚本后报错

**Traceback (most recent call last):
  File "<stdin>", line 52, in <module>
AssertionError**

**Comment by nondanee** [comment]
@ofcZsgj 
现在 windows 版应该是不用替换的，应该不会是 ffmpeg 的问题
你看看 webview 调试工具里有没有报错吧

assert 在这个位置
https://gist.github.com/nondanee/f157bbbccecfe29e48d87273cd02e213#file-helper-py-L52
也就是说没检测到你的安装位置，是不是改过默认安装位置呢？

**Comment by ofcZsgj** [comment]
对，VS CODE没安在默认位置
是因为这个的原因嘛

**Comment by nondanee** [comment]
@ofcZsgj 
嗯改过位置执行脚本会报错的
但是 windows 上应该是不用替换的，可能是网络问题，麻烦提供一下 webview 的日志

如果你想替换试试看
需要把脚本下载下来
https://gist.githubusercontent.com/nondanee/f157bbbccecfe29e48d87273cd02e213/raw
把第 20 行改成自己的安装位置后再执行

**Comment by Kennethws** [comment]
> @ofcZsgj
> 现在 windows 版应该是不用替换的，应该不会是 ffmpeg 的问题
> 你看看 webview 调试工具里有没有报错吧
> [](url)
> assert 在这个位置
> https://gist.github.com/nondanee/f157bbbccecfe29e48d87273cd02e213#file-helper-py-L52
> 也就是说没检测到你的安装位置，是不是改过默认安装位置呢？

你好我是Win10，VS code更新到了最新版本，但是启动插件后也没有声音，报错信息如下：
<img width="603" alt="Capture" src="https://user-images.githubusercontent.com/52492959/60588549-d5a72880-9dc9-11e9-9444-d84da8ef9c86.PNG">
<img width="611" alt="1" src="https://user-images.githubusercontent.com/52492959/60588571-e0fa5400-9dc9-11e9-9b45-9c5d5c9e0223.PNG">
关于Interact，我已经打开了webview，所以不清楚是为什么

**Comment by nondanee** [comment]
@Kennethws 
这位同学，我看到邮件有你的 reply，请问是已经解决了吗？

**Comment by Kennethws** [comment]
同学你好，现在播放已经没有问题了，但我并不知道是为什么，感觉突然就好了。因为我记得上次关闭的时候没有做任何改动。可能跟重启有关？

**Comment by nondanee** [comment]
@Kennethws 
无关，要求 interact 就只要在那个自动打开的空白 tab 里任何位置点击一下就行了

**Comment by Kennethws** [comment]
嗯我之前也是这么做的，但是没成功，然后刚刚就成功了。不过没问题就好了，多谢你特地回复我啦😊
这个插件真的太骚了👍

**Comment by Kennethws** [comment]
同学你好，不好意思再次打扰你。我在使用插件的时候又出现了问题。具体表现为启动了插件，互动了之后，下方虽然出现了播放曲目，但是无法播放。单击播放键没有作用。截图是developer视角的一些信息，但是我看不太懂。请问能替我看下是什么问题吗？非常感谢！

**Comment by nondanee** [comment]
@Kennethws 
我看不见图==
是 vscode 更新到 1.36 了吧？
现在 Windows 也需要替换 ffmpeg.dll 了 #50 #52

**Comment by Kennethws** [comment]
没错没错，前几天确实是更新了。好的我来看一下#50 #52。如果还有问题再来请教，非常感谢！

**Comment by Kennethws** [comment]
同学你好，我本来准备根据插件的使用说明替换ffmpeg，但里面提供的Manual
Replacement的链接都失效了。我还想请问一下，那个ffmpeg所在位置要怎么打开？我看了那些issue不是很明白。打扰到你啦不好意思。

**Comment by nondanee** [comment]
@Kennethws 
Manual Replacement 里的链接需要你自己替换里面的 `%version%` 为你实际安装的版本
比如 vscode 1.36.1, electron 4.2.5
yarnrc 文件 `https://raw.githubusercontent.com/Microsoft/vscode/1.36.1/.yarnrc`
electron release `https://github.com/electron/electron/releases/tag/v4.2.5`

ffmpeg.dll 在 vscode 安装根目录
觉得麻烦的话可以用脚本替换

**Comment by Kennethws** [comment]
同学你好，我打开了第二个链接，但是我不知道该下载下面的哪一个zip,其他都是对应的，但是win32后面的部分我不太明白。我选的是x64（下划线的）。然后还有一个问题是，我把压缩包解压之后直接复制到vscode根目录里面，替换了很多东西，然后vscode直接打不开了，所以我想我应该还是没理解到底怎么替换ffmpeg.dll。。。是只需要压缩包解压之后里面的ffmpeg.dll一个文件吗？以及第一个链接打开是这样的，我不确定是不是就是这个意思。
[image: Capture.PNG]
[image: Capture.PNG]

**Comment by nondanee** [comment]
@Kennethws 
一般来说是 electron-v4.2.5-win32-x64.zip 这个
对只要换 ffmpeg.dll 这一个文件
我看不到图==

**Comment by Kennethws** [comment]
啊不好意思。。。好的那我之后重新弄一下。麻烦你啦🙇

**Comment by Kennethws** [comment]
同学你好，我现在可以运行插件了。真的非常感谢你的帮助！
