### ISSUE TITLE
Windows Powershell Permission Error

### ISSUE THREAD

**Issue by 4AHZ** [nondanee/vsc-netease-music#97]
Hi,
I've used the unix version of the extension and it works great! However, when I tried to do the same in Windows, it gives me an error 
**Traceback (most recent call last):
  File "<stdin>", line 68, in <module>
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\scupi\\AppData\\Local\\Programs\\Microsoft VS Code\\ffmpeg.dll'**
I'm pretty sure I'm running the powershell in Administrator mode, I'm using 1.46.1 x64 version of vscode & 7.3.1 electron. Could someone help me? Thanks!

**Comment by yk6** [comment]
You may need to close VS code while you run this script

**Comment by 4AHZ** [comment]
> You may need to close VS code while you run this script

That works thanks!
